services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1435:1433"
    env_file:
      - .env.docker
    environment:
      - ACCEPT_EULA=Y

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: HireMatch.WebAPI/Dockerfile
    ports:
      - "5086:5086"
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5086
    depends_on:
      - sqlserver
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: HireMatch.Worker/Dockerfile
    env_file:
      - .env.docker
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_started