// <auto-generated />
using System;
using HireMatch.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HireMatch.Services.Migrations
{
    [DbContext(typeof(HireMatchDbContext))]
    [Migration("20260615150636_AddCareerTips")]
    partial class AddCareerTips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HireMatch.Services.Database.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobPostId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("HireMatch.Services.Database.ApplicationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reviewed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sent to client"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technical interview"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Final stage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MyAppUserId")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("HireMatch.Services.Database.CandidatePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidatePreferences");
                });

            modelBuilder.Entity("HireMatch.Services.Database.CandidateStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CandidateStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open to full-time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Open to part-time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Open to freelance/contract"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Open to internship"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Not actively looking"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.CareerTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerTips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Keep it concise, use action verbs, and tailor it to each job. Highlight measurable achievements rather than just listing duties.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "✨",
                            Title = "How to make your CV stand out"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Communication, teamwork and problem-solving consistently rank highest. Show examples of these in your interviews.",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "💬",
                            Title = "Top 3 soft skills recruiters love"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Apply for internships, contribute to open-source projects, or take on freelance work to build your portfolio.",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "🚀",
                            Title = "Don't have experience? Here's what to do"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Zagreb"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            Name = "Split"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Name = "Rijeka"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Name = "Osijek"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Name = "Varaždin"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Beograd"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            Name = "Novi Sad"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 3,
                            Name = "Nis"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            Name = "Kragujevac"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 3,
                            Name = "Subotica"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 4,
                            Name = "Ljubljana"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 4,
                            Name = "Maribor"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 4,
                            Name = "Celje"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 4,
                            Name = "Kranj"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 4,
                            Name = "Koper"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Name = "Podgorica"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Name = "Nikšic"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Name = "Herceg Novi"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            Name = "Kotor"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 5,
                            Name = "Budva"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hrvatska"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Srbija"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Slovenija"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crna Gora"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Full-time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Part-time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Internship"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Remote"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Contract"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobPostId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beauty & Fashion"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Legal"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Compensation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobPostSkill", b =>
                {
                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobPostId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobPostSkills");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobPostId");

                    b.ToTable("JobViews");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobPostId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HireMatch.Services.Database.MyAppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidateStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateStatusId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("MyAppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hirematch.com",
                            FirstName = "Admin",
                            IsPremium = false,
                            LastName = "System",
                            PasswordHash = "Admin123!",
                            Phone = "000-000-000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            Name = "C#"
                        });
                });

            modelBuilder.Entity("HireMatch.Services.Database.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("HireMatch.Services.Database.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Application", b =>
                {
                    b.HasOne("HireMatch.Services.Database.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("ApplicationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.JobPost", "JobPost")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("Candidate");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Candidate", b =>
                {
                    b.HasOne("HireMatch.Services.Database.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HireMatch.Services.Database.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "MyAppUser")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("HireMatch.Services.Database.Candidate", "MyAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("MyAppUser");
                });

            modelBuilder.Entity("HireMatch.Services.Database.CandidatePreference", b =>
                {
                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId");

                    b.HasOne("HireMatch.Services.Database.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.HasOne("HireMatch.Services.Database.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("Candidate");

                    b.Navigation("EmploymentType");

                    b.Navigation("Industry");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HireMatch.Services.Database.City", b =>
                {
                    b.HasOne("HireMatch.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Favourite", b =>
                {
                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.JobPost", "JobPost")
                        .WithMany("Favourites")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobPost", b =>
                {
                    b.HasOne("HireMatch.Services.Database.Company", "Company")
                        .WithMany("JobPosts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.EmploymentType", "EmploymentType")
                        .WithMany("JobPosts")
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("EmploymentType");

                    b.Navigation("Industry");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobPostSkill", b =>
                {
                    b.HasOne("HireMatch.Services.Database.JobPost", "JobPost")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.Skill", "Skill")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobView", b =>
                {
                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.JobPost", "JobPost")
                        .WithMany("JobViews")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Message", b =>
                {
                    b.HasOne("HireMatch.Services.Database.JobPost", "JobPost")
                        .WithMany("Messages")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HireMatch.Services.Database.MyAppUser", b =>
                {
                    b.HasOne("HireMatch.Services.Database.CandidateStatus", null)
                        .WithMany("Users")
                        .HasForeignKey("CandidateStatusId");

                    b.HasOne("HireMatch.Services.Database.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId");

                    b.HasOne("HireMatch.Services.Database.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Notification", b =>
                {
                    b.HasOne("HireMatch.Services.Database.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireMatch.Services.Database.UserActivityLog", b =>
                {
                    b.HasOne("HireMatch.Services.Database.MyAppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireMatch.Services.Database.UserSkill", b =>
                {
                    b.HasOne("HireMatch.Services.Database.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireMatch.Services.Database.MyAppUser", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireMatch.Services.Database.CandidateStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HireMatch.Services.Database.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Company", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HireMatch.Services.Database.EmploymentType", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("HireMatch.Services.Database.JobPost", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Favourites");

                    b.Navigation("JobPostSkills");

                    b.Navigation("JobViews");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HireMatch.Services.Database.MyAppUser", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("HireMatch.Services.Database.Skill", b =>
                {
                    b.Navigation("JobPostSkills");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
