name: hirematch_admin
description: "HireMatch admin desktop (Windows) application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  pdf: ^3.11.1
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
